spring.application.name=yacht-backend
server.servlet.context-path=/api

spring.profiles.active=dev

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
spring.sql.init.mode=never

spring.jpa.open-in-view=false
spring.datasource.hikari.maximum-pool-size=30

jwt.expiration=900
jwt.refresh_expiration=86400

game.rule.turn_limit_minutes=3
game.rule.user_limit_per_room=4